### PR TITLE
Added database migration tool Liquibase and In memory test database

### PR DESCRIPTION
**Pull request by josh-mchugh**

### CODE REVIEW

**Comment by ryonsteele** [comment]
This is awesome! Going to pull it down and try it from my desktop this weekend.
I'm trying to get it setup till i get new macbook.

**Comment by josh-mchugh** [comment]
Here are some quick links for the weekend. Just install docker locally and run the following commands. This postgres will run in a container and start on boot with the'restart=always' flag enabled. 


Docker Postgres Command: 

docker run --restart=always -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres

pgAdmin Download link: 

https://www.pgadmin.org/download/

**Review by ryonsteele — APPROVED** [review]

**Comment by ryonsteele** [comment]
When I run the installer for Docker it gives a funny error:
[image: image.png]

My version is higher than that so no idea why its complaining, ill figure
that out later.

pgAdmin 4 is freaking awesome. Love the interface. thanks for that better
than query by command line!

With Liquidbase. Any idea how to generate the changelog for already
existing DB?
The only way I could get the project to launch due to "Error relation
appusers table already exists"
Was to drop all tables and create fresh.

**Comment by josh-mchugh** [comment]
Unfortantly the image didn't load so I am not able to see the funny error.

I believe the easiest way to sync and existing database with liquibase that is pre-production is to create drop. There is a maven command that can help to though. https://docs.liquibase.com/tools-integrations/maven/commands/maven-changelogsync.html

Additional documentation:
https://docs.liquibase.com/workflows/liquibase-community/existing-project.html

**Comment by josh-mchugh** [comment]
If you get a chance checkout the `databasechangelog` table. This is Liquibase's table which knows what change log have been executed. The XML I wrote has one change log which creates all the tables. This would explain why there is only one row within this table with the author being `jmchugh` and ID being `1`. 

When Spring Boot starts up, it goes through the XML and compares the change log database table to the file. This way if the change log with ID+ author already executed, it will not execute again. What makes a change log unique is the ID and the author cominded. Liquibse stores this as a MD5 check sum. The server will not run if these rules are violated or some type of SQL error during liquibase's migration. This is a benefit of failing fast which will break local enviroments before shared enviroments (dev, qa, stage, prod). 

I recommend always incrementing the ID even if the author is different as it helps keep track of things from a development prespective. 

This is nice as your local database, development server, qa server, stage, and production server will always be in sync as the code deploys in new enviroments. Also it's really easy to teardown and rebuild new databases as you experianced earlier.

**Pull request merged**
